version: '3.8'
services:
  note-db:
    container_name: note_db
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - note-data:/var/lib/postgresql/data
  app:
    container_name: note_app
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  note-data: