apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "50051"
  DB_NAME: "auth-db-"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  DB_USERNAME: "auth-user"
  DB_PASSWORD: "auth-password"
  DB_CONNECTION_STRING: "postgresql://auth-user:auth-password@auth-db-service:5432/auth-db"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: auth-db-pod

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db-statefulset
spec:
  serviceName: auth-db-service
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-pod
  template:
    metadata:
      labels:
        app: auth-db-pod
    spec:
      containers:
        - name: auth-db-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_NAME
          volumeMounts:
            - name: auth-db-volume
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: auth-db-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod
    spec:
      containers:
        - name: auth-service-container
          image: ghcr.io/zvnico/cloud-integration/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_CONNECTION_STRING

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051