apiVersion: v1
kind: ConfigMap
metadata:
  name: note-app-config
data:
  AUTH_SERVICE_URL: "auth-service:80"
  PORT: "3000"
  DB_NAME: "note-db"

---
apiVersion: v1
kind: Secret
metadata:
  name: note-app-secret
type: Opaque
stringData:
  DB_USERNAME: "note-user"
  DB_PASSWORD: "note-password"
  DB_CONNECTION_STRING: "postgresql://note-user:note-password@note-db-service:5432/note-db"

---
apiVersion: v1
kind: Service
metadata:
  name: note-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: note-db-pod

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: note-db-statefulset
spec:
  serviceName: note-db-service
  replicas: 1
  selector:
    matchLabels:
      app: note-db-pod
  template:
    metadata:
      labels:
        app: note-db-pod
    spec:
      containers:
        - name: note-db-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: note-app-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: note-app-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: note-app-config
                  key: DB_NAME
          volumeMounts:
            - name: note-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: note-db
  volumeClaimTemplates:
    - metadata:
        name: note-db-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app-pod
  template:
    metadata:
      labels:
        app: note-app-pod
    spec:
      containers:
        - name: note-app-container
          image: ghcr.io/zvnico/cloud-integration/note-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: note-app-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: note-app-secret
                  key: DB_CONNECTION_STRING
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: note-app-config
                  key: AUTH_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: note-app-service
spec:
  selector:
    app: note-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note-app-ingress
spec:
  rules:
    - host: "34.49.160.154"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: note-app-service
                port:
                  number: 80