version: '3.8'
services:
  auth-db:
    container_name: auth_db
    image: postgres
    restart: always
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
  service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  auth-data: