name: Build and Push Auth-Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push auth-service image
        uses: docker/build-push-action@v2
        with:
          context: ./auth-service
          push: true
          tags: ghcr.io/${{ github.repository }}/auth-service:latest