name: Deploy Auth-Service to GKE

on:
  workflow_run:
    workflows: [ "Build and Push Auth-Service Docker Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Set GKE Context
        run: |
          gcloud container clusters get-credentials cluster-1 --zone europe-west1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/auth-service.yaml